name: CI Build and Notify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Send Success Email
        uses: dawidd6/action-send-mail@v6
        with:
          # ✅ Use connection_url format for simplicity (secure & clear)
          connection_url: ${{ secrets.MAIL_CONNECTION }}

          # ✅ Sender and recipient
          to: khushid830@gmail.com
          from: CI Bot <noreply@example.com>

          # ✅ Email content
          subject: ✅ Build Success - ${{ github.repository }}
          body: |
            Hello Khushi 👋,

            The latest build for **${{ github.repository }}** on branch **${{ github.ref }}** has completed successfully!

            ✅ Commit: ${{ github.sha }}
            📦 Triggered by: ${{ github.actor }}
            🔗 Check the build: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            — GitHub Actions CI
